### ISSUE TITLE
Error when running 'npm run watch'

### ISSUE THREAD

**Issue by doc-jay** [WietseWind/PayID-Static#1]
OS:  Centos 7

git cloned the code to /opt/PayID-Static
ran 'npm install'
Initially I was running 'npm run watch' but it errors with 'start' as well.
When I ran 'npm run start' it stops and errors with:

[npm-debug.log](https://github.com/WietseWind/PayID-Static/files/4800190/npm-debug.log)

**Comment by doc-jay** [comment]
debug log attached -- 

additional output from the console:

> payid-static@0.1.0 watch /opt/PayID-Static
> DEBUG=payid-server* nodemon index.js

/opt/PayID-Static/node_modules/chokidar/index.js:151
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/PayID-Static/node_modules/nodemon/lib/monitor/watch.js:6:16)

npm ERR! Linux 3.10.0-1127.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! payid-static@0.1.0 watch: `DEBUG=payid-server* nodemon index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the payid-static@0.1.0 watch script 'DEBUG=payid-server* nodemon index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the payid-static package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=payid-server* nodemon index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs payid-static
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls payid-static
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/PayID-Static/npm-debug.log

**Comment by WietseWind** [comment]
@doc-jay Looks like you are running an old node version without async support.

What's the output of `node -v`?

It should be 8.x or up.
